version: '2'
services:
  db:
    container_name: cipudda_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cipudda
      MYSQL_USER: cipudda
      MYSQL_PASSWORD: cipudda

